### ISSUE TITLE
豆瓣好像改 API 了 最近的不能用了

### ISSUE THREAD

**Issue by aristotll** [xinhangliu/alfred-workflow#1]
如题 谢谢

**Comment by najunuoyan** [comment]
是的，提示异常请求。

**Comment by xinhangliu** [comment]
豆瓣开发者平台貌似已经进不去了，但是现在 API 接口还能用，我这边测试了下暂时还可以。

**Comment by liyang85** [comment]
搜索电影、音乐都可以出结果，但搜索书籍就是 `Error: Forbidden`，开发者能否帮忙看看是否可以解决？多谢。

**Comment by bosconb** [comment]
试了试，全是Error: Forbidden，求更新
